---
inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-config: default.yml

AllCops:
  TargetRubyVersion: "3.1"
  SuggestExtensions: False
  NewCops: enable

RSpec/NestedGroups:
  Enabled: False

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/restify/features/**/*.rb
