AllCops:
  Include:
    - '**/*.gemspec'
    - '**/Rakefile'

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/RaiseArgs:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/CaseIndentation:
  IndentWhenRelativeTo: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: true

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - '**/*.gemspec'
