AllCops:
  Include:
    - '**/*.rb'
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: true
  SupportedStyles:
    - case
    - end

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space


Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/LineLength:
  Exclude:
    - spec/**/*_spec.rb


Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SignalException:
  EnforcedStyle: only_raise

Style/TrivialAccessors:
  AllowPredicates: true
