dist: xenial
cache: bundler
language: ruby
bundler_args: "--without development"
before_install:
- gem update --system
- gem install bundler -v '~> 1.17'
- gem install bundler -v '~> 2.0'
rvm:
- 2.6.0
- 2.5.3
- 2.4.5
- 2.3.8
env:
- ADAPTER=em
- ADAPTER=em-pooled
- ADAPTER=typhoeus
- ADAPTER=typhoeus-sync
jobs:
  include:
  - stage: Release
    rvm: 2.6.0
    env: []
    script: skip
    install: skip
    deploy:
      provider: rubygems
      api_key:
        secure: B+xnOLyevbhS/h7zYDlGgSWBSsq9qsZ+OPBnzCF+QN8MJKhQUP3sIT0zX1bCG/pRwijiYirx1aO1wuQgp0vM0Lh58wzrEPGTTgBEvHkak5/4yFGQbLrN6gBGpBPxcF6oo0o8WJO8gYNb3zoqFQ2WUa99/PMT3Tg/+lcUF3aE0YM=
      gem: restify
      on:
        tags: true
        repo: jgraichen/restify
