sudo: false
language: ruby
cache: bundler
bundler_args: --without development
before_install:
- gem update --system
- gem install bundler
before_script:
- export JRUBY_OPTS="--2.0"
rvm:
- '2.3.1'
- '2.2.5'
- '2.1.10'
- rbx-2
- rbx-3
- jruby
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
    - rvm: rbx-3
env:
- ADAPTER=em-http-request
- ADAPTER=typhoeus
- ADAPTER=typhoeus-sync
