sudo: false
dist: trusty
language: ruby
cache: bundler
bundler_args: "--without development"
before_install:
- gem update --system
- gem install bundler
rvm:
- 2.5.3
- 2.4.5
- 2.3.8
- 2.2.10
env:
- ADAPTER=em
- ADAPTER=em-pooled
- ADAPTER=typhoeus
- ADAPTER=typhoeus-sync
jobs:
  include:
  - stage: Release
    rvm: 2.5.3
    env: []
    script: skip
    install: skip
    deploy:
      provider: rubygems
      api_key:
        secure: B+xnOLyevbhS/h7zYDlGgSWBSsq9qsZ+OPBnzCF+QN8MJKhQUP3sIT0zX1bCG/pRwijiYirx1aO1wuQgp0vM0Lh58wzrEPGTTgBEvHkak5/4yFGQbLrN6gBGpBPxcF6oo0o8WJO8gYNb3zoqFQ2WUa99/PMT3Tg/+lcUF3aE0YM=
      gem: restify
      on:
        tags: true
        repo: jgraichen/restify
