sudo: false
language: ruby
cache: bundler
bundler_args: --without development
rvm:
- '2.2'
- '2.1'
- '2.0'
- jruby
- rbx-2
env:
- ADAPTER=em-http-request
- ADAPTER=typhoeus
- ADAPTER=celluloid
matrix:
  allow_failures:
  - rvm: jruby
  - rvm: rbx-2
deploy:
  provider: rubygems
  api_key:
    secure: fAr3oAAHOmg4Kb0lOPnvBIHkTLnatQRf5nQbSWq1yhsJPPDufD1QSNFgKHWXviWM5pU+vja++mquzNu8Xkqc0eIJ4fk+z+5JDqL85WnWgBaZsw64jbDO9umoUBqwrFnFDM192WrCeY3Mc2s5KjGoLgS+D0LzcRC4FOeJXsustRE=
  gem: restify
  on:
    branch: master
    rvm: '2.2'
