sudo: false
language: ruby
cache: bundler
bundler_args: --without development
before_install:
- gem update --system
- gem install bundler
before_script:
- export JRUBY_OPTS="--2.0"
rvm:
- '2.4.0'
- '2.3.3'
- '2.2.6'
- jruby-9
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-9
env:
- ADAPTER=em-http-request
- ADAPTER=typhoeus
- ADAPTER=typhoeus-sync
