sudo: false
language: ruby
cache: bundler
bundler_args: --without development
before_script:
- export JRUBY_OPTS="--2.0"
rvm:
- '2.3.0'
- '2.2'
- '2.1'
- rbx-2
- jruby
matrix:
  allow_failures:
    - rvm: jruby
env:
- ADAPTER=em-http-request
- ADAPTER=typhoeus
