dist: bionic
cache: bundler
language: ruby
bundler_args: "--without development"
rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - 2.4.10
  - 2.3.8
env:
  - ADAPTER=em
  - ADAPTER=em-pooled
  - ADAPTER=typhoeus
  - ADAPTER=typhoeus-sync
