sudo: false
language: ruby
cache: bundler
rvm:
- '2.1'
- '2.0'
- 1.9.3
- jruby
- rbx-2
matrix:
  allow_failures:
  - rvm: jruby
  - rvm: rbx-2
deploy:
  provider: rubygems
  api_key:
    secure: fAr3oAAHOmg4Kb0lOPnvBIHkTLnatQRf5nQbSWq1yhsJPPDufD1QSNFgKHWXviWM5pU+vja++mquzNu8Xkqc0eIJ4fk+z+5JDqL85WnWgBaZsw64jbDO9umoUBqwrFnFDM192WrCeY3Mc2s5KjGoLgS+D0LzcRC4FOeJXsustRE=
  gem: restify
  on:
    branch: master
    rvm: '2.1'
