sudo: false
language: ruby
cache: bundler
bundler_args: --without development
before_script:
- export JRUBY_OPTS="--2.0"
rvm:
- '2.2'
- '2.1'
- '2.0'
- rbx-2
env:
- ADAPTER=em-http-request
- ADAPTER=typhoeus
