# vim: ft=yaml

name: release

on:
  push:
    tags:
      - v*

jobs:
  rubygems:
    if: github.repository == 'jgraichen/restify'
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073 # v1.324.0
        with:
          ruby-version: ruby
          bundler-cache: false
        env:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 10

      - uses: rubygems/release-gem@052cc82692552de3ef2b81fd670e41d13cba8092 # v1.4.0

      - uses: taiki-e/create-gh-release-action@eba8ea96c86cca8a37f1b56e94b4d13301fba651 # v1.11.0
        with:
          changelog: CHANGELOG.md
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
