---
name: test

on:
  - push
  - pull_request
  - workflow_dispatch

permissions:
  contents: read

jobs:
  rspec:
    name: "${{ matrix.ruby }} / ${{ matrix.adapter }}"
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "4.0"
          - "3.4"
          - "3.3"
          - "3.2"
          - "3.1"
        adapter:
          - ethon
          - typhoeus
          - typhoeus-sync

    env:
      BUNDLE_WITHOUT: development
      ADAPTER: ${{ matrix.adapter }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073 # v1.324.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
        env:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3

      - run: |
          bundle exec rspec --color --format documentation

      - uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  rubocop:
    name: rubocop
    runs-on: ubuntu-24.04

    env:
      BUNDLE_WITHOUT: development

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073 # v1.324.0
        with:
          ruby-version: "4.0.5"
          bundler-cache: true
        env:
          BUNDLE_WITHOUT: development
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3

      - run: bundle exec rubocop --parallel --fail-level E
